[package]
name = "GameSaveServer"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
tokio = { version = "1.47.1", features = ["full"] }
serde = { version = "1.0.225", features = ["derive"] }
tracing-subscriber = "0.3.20"
diesel = { version = "2.3.2", features = ["sqlite", "serde_json", "r2d2"] }
diesel_migrations = "2.3.0"
once_cell = "1.21.3"
utoipa = { version = "5.4.0", features = ["axum_extras"] }
utoipa-swagger-ui = { version = "9.0.2", features = ["axum"] }

